services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5600:5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=hackathon
      - POSTGRES_DB=hackathon
